server:
  name: "na-practice"
  type: "practice"
messages:
  welcome:
    - "&7&m--------------------------------------------"
    - "&6Welcome to &6&lPvP Camp!"
    - "&6Discord: &fdiscord.gg/4F39Qh8dHJ"
    - "&6Store: &fstore.pvp.camp"
    - " "
    - "&cNOTICE: &fWe are still in early beta. Please report any bugs to the developers."
    - "&7&m--------------------------------------------"
  announcements:
    - "&7[&6&lPvP Camp&7] &6Like our server on NameMC for a free rank! &fnamemc.com/server/pvp.camp"
    - "&7[&6&lPvP Camp&7] &6Ranks and tags are now available on our store! &fstore.pvp.camp"
    - "&7[&6&lPvP Camp&7] &6Join our Discord: &fdiscord.gg/4F39Qh8dHJ"
networking:
  mongo:
    uri: "uri"
    database: "db"
    chat_history_collection: "core_chat_history"
    grants_collection: "core_grants"
    profiles_collection: "core_profiles"
    punishments_collection: "core_punishments"
    ranks_collection: "core_ranks"
    tags_collection: "core_tags"
  redis:
    host: "127.0.0.1"
    port: 6379
tablist:
  header: "&6&lPvP Camp"
  footer: "&6You are currently playing on &fLobby&6."
chat:
  enabled: true
  cooldown: 3
namemc:
  api_server: "pvp.camp"