server:
  name: "na-practice"
  type: "practice"
messages:
  welcome:
    - "&7&m--------------------------------------------"
    - "&6Welcome to &6&lPvP Camp!"
    - "&6Discord: &fdiscord.gg/4F39Qh8dHJ"
    - "&6Store: &fstore.pvp.camp"
    - " "
    - "&cNOTICE: &fWe are still in early beta. Please report any bugs to the developers."
    - "&7&m--------------------------------------------"
  announcements:
    1:
      - " "
      - "&6&lPvP Camp"
      - "&6Like our server on NameMC for a free rank! &fnamemc.com/server/pvp.camp"
      - " "
    2:
      - " "
      - "&6&lPvP Camp"
      - "&6Ranks and tags are now available on our store! &fstore.pvp.camp"
      - " "
    3:
      - " "
      - "&6&lPvP Camp"
      - "&6Join our Discord: &fdiscord.pvp.camp"
      - " "
networking:
  mongo:
    uri: "uri"
    database: "db"
    chat_history_collection: "chat_history"
    grants_collection: "grants"
    profiles_collection: "profiles"
    punishments_collection: "punishments"
    ranks_collection: "ranks"
    tags_collection: "tags"
  redis:
    host: "127.0.0.1"
    port: 6379
chat:
  enabled: true
  cooldown: 3
namemc:
  api_server: "pvp.camp"
ipgeolocation:
  api_key: "key"