name: Core
version: ${git.branch}-${git.commit.id.abbrev}
main: camp.pvp.core.Core
author: leuo
depend:
  - Gooey2
softdepend:
  - ProtocolLib
commands:
  alert:
    description: Send an alert to all players.
    permission: core.commands.alert
  alts:
    description: View the alts of a player.
    permission: core.commands.alts
  auth:
    aliases: [2fa]
    description: Authenticate your account.
  ban:
    aliases: [b]
    description: Ban a player permanently.
    permission: core.commands.ban
  blacklist:
    aliases: [bl]
    description: Blacklist a player permanently.
    permission: core.commands.blacklist
  chat:
    description: Mute, unmute, or slow global chat.
    permission: core.commands.chat
  color:
    aliases: [colors, colour, colours, chatcolor, chatcolors, chatcolour, chatcolours]
    description: Change the color of your name.
    permission: core.commands.color
  demo:
    description: Puts a player into demo mode and crashes their client.
    permission: core.commands.demo
  feed:
    description: Feed a player.
    permission: core.commands.feed
  flighteffects:
    description: Customize your flight effects.
  grant:
    description: Add, remove, or show the grants of a player.
    permission: core.commands.grant
  granthistory:
    aliases: [granthist, ghistory, ghist]
    description: Look at the grant history of a player.
    permission: core.commands.granthistory
  grants:
    description: Open the grants GUI.
    permission: core.commands.grants
  helpop:
    aliases: [request]
    description: Send a request to online staff.
  history:
    aliases: [hist, check, c]
    description: View the punishment history of a player.
    permission: core.commands.history
  ignore:
    aliases: [block]
    description: Ignore a player from PMs and global chat.
  invalidate:
    description: Invalidate a player's core profile.
    permission: core.commands.invalidate
  inventorysee:
    aliases: [invsee]
    description: View the inventory of a player.
    permission: core.commands.inventorysee
  kick:
    description: Kick a player from the server.
    permission: core.commands.kick
  list:
    description: View the list of players online.
  message:
    aliases: [msg, pm, message, reply, r]
    description: Message a player.
  more:
    description: Get a full stack of any item in your hand.
    permission: core.commands.more
  mute:
    description: Mute a player permanently.
    permission: core.commands.mute
  playtime:
    aliases: [pt]
    description: View the playtime of a player.
    permission: core.commands.playtime
  rank:
    description: Rank manager.
    permission: core.commands.rank
  report:
    description: Report a player.
  skull:
    description: Get the head of a player.
    permission: core.commands.skull
  sounds:
    description: Enable or disable message sounds.
  staffchat:
    aliases: [sc]
    description: Enable or disable staff chat.
    permission: core.commands.staffchat
  staffhistory:
    aliases: [shistory, shist]
    description: View the staff history of a staff member.
    permission: core.commands.staffhistory
  tagmanager:
    aliases: [tmanager, tagm]
    description: Tag manager.
    permission: core.commands.tagmanager
  tags:
    description: View and apply a chat tag.
  teleport:
    aliases: [tp, tphere, teleporthere, tppos, tpp, teleportpos]
    description: Teleport to a player or position, or teleport a player to a player or position.
    permission: core.commands.teleport
  tempban:
    aliases: [tban]
    description: Temporarily ban a player.
    permission: core.commands.tempban
  tempmute:
    aliases: [tm, tmute]
    description: Temporarily mute a player.
    permission: core.commands.tempmute
  timezone:
    description: Set your timezone.
    aliases: [tz]
  toggleglobalchat:
    aliases: [tgc]
    description: Enable or disable global chat.
  togglemessages:
    aliases: [messages, tpm]
    description: Enable or disable private messages.
  unban:
    aliases: [ub]
    description: Unban a player.
    permission: core.commands.unban
  unblacklist:
    aliases: [unbl]
    description: Unblacklist a player.
    permission: core.commands.unblacklist
  unignore:
    aliases: [unblock]
    description: Unignore a player.
  sudo:
    description: Send a chat or run a command as another player.
    permission: core.commands.sudo
  seen:
    description: View the last login of a player.
    permission: core.commands.seen
  playerlookup:
    aliases: [lookup, playerinfo, pinfo]
    description: View the information of a player.
    permission: core.commands.playerlookup
  tag:
    description: Add, remove, or list the tags of a player.
    permission: core.commands.tag
  serverinfo:
    description: View the server information.
    permission: core.commands.serverinfo
  unmute:
    description: Unmute a player.
    permission: core.commands.unmute
  userhistory:
    aliases: [userhist, uhistory, uhist]
    description: View the chat, command, and PM history of a player.
    permission: core.commands.userhistory
  heal:
    description: Heal a player.
    permission: core.commands.heal
  gamemode:
    aliases: [gmc, gms, gm, survival, creative]
    description: Change the gamemode of a player.
    permission: core.commands.gamemode
  fly:
    description: Enable or disable flight for a player.
    permission: core.commands.fly